name: Deploy SWA (prebuilt Blazor WASM)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish Blazor WASM
        run: dotnet publish -c Release -o release

      - name: Deploy to Azure Static Web Apps (skip build)
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_RIVER_0198C230F }}
          app_location: /
          output_location: release/wwwroot
          skip_app_build: true
